### ISSUE TITLE
Screen jitters when updating offscreen views

### ISSUE THREAD

**Issue by NateNate60** [CrazyPyroEagle/ToS-TextClient#1]
When ending a game the screen freaks out a bit redrawing itself a couple times. Resizing the window and pressing the space bar and waiting a bit appears to fix this issue, so nothing game-breaking.

**Comment by CrazyPyroEagle** [comment]
What version was that? All versions up to 1.3.3.0 fixed some major graphical issues.
Could you describe the issue and the moment it occurred in more detail?

**Comment by NateNate60** [comment]
I believe it was 1.3.3.0, but I was running the game in a small window. It doesn't happen when I check "run maximised" so it may be a small screen/low-resolution issue.

**Comment by CrazyPyroEagle** [comment]
The client will render side views offscreen, but this comes with the unfortunate side-effect of the screen moving (in the latest commit it immediately snaps the screen back after drawing, but jittering is still visible) because there is no way of drawing offscreen without moving the screen's view of the buffer.

I will look into drawing onscreen then moving the drawn content offscreen (the only way of drawing offscreen). The alternative is that I disable offscreen drawing altogether for side views, but that makes it impossible to use scrolling to look at offscreen views.

**Comment by CrazyPyroEagle** [comment]
I've decided to not draw offscreen, but add key-based scrolling.
I'm currently rewriting the drawing code to fix this.

**Comment by NateNate60** [comment]
OK, good. Also, scrolling doesn't seem to work since whenever anyone says anything the screen re-scrolls back to the bottom. Therefore, the chatlog is completely useless because the only time you can feasibly scroll it is at night, when you need it the least. I imagine it's also hell for _jailers_ and those with nightchat.

**Comment by CrazyPyroEagle** [comment]
Key-based scrolling will solve that too.
